### ISSUE TITLE
How do you create a campaign?

### ISSUE THREAD

**Issue by nickbyte** [spatie/laravel-newsletter#110]

**Comment by focusiq** [comment]
I am also trying to get how to send campaigns from Laravel using the package. Were you able to get around it?

**Comment by sebastiandedeyne** [comment]
You can create a campaign with the `createCampaign` method.

https://github.com/spatie/laravel-newsletter#creating-a-campaign

This package doesn't support sending it out though, gonna need to do that via the interface. Not sure if there's an API endpoint for that, we'd consider accepting a PR for that if there is.

**Comment by Lorddubbs1** [comment]
Can we send campaigns via Spatie now? It's 2018.

**Comment by freekmurze** [comment]
@Lorddubbs1 We don't need to send campaigns in our projects. That's why it's the functionality is not in the package.

 Here are your options:
- do what @sebastiandedeyne suggested above
- submit a well tested, well documented PR and we'll consider adding it to the package if the code required is simple enough
- fork our code, add the functionality there and maintain it yourself
- use another package
- pay us to add it for you
