### ISSUE TITLE
API key as variable

### ISSUE THREAD

**Issue by stijnvanouplines** [spatie/laravel-newsletter#43]
Hi there,

Is it possible to insert the API key as a variable to the config file? Now I have an application with one user. The API key is in the .env file. I want to expand my application so I can add more users. I have all settings (API key,...) of all users in a database.

Thanks,
Stijn

**Comment by sebastiandedeyne** [comment]
Not out of the box, since the `Newsletter` class is registered as a singleton with the API key as a constructor argument. If you're dealing with multiple users, I'd suggest not registering this package to your application, but creating instances of the underlying classes yourself.

Setting up a `Newsletter` instance isn't too much of a hassle: https://github.com/spatie/laravel-newsletter/blob/master/src/NewsletterServiceProvider.php#L23

**Comment by dambridge** [comment]
@sebastiandedeyne Sorry for the necrobump, just curious how you might recommend doing that? (setting up a `Newsletter` instance instead of using singleton)

**Comment by sebastiandedeyne** [comment]
Whipped up a quick example, not promising it will work as is 😅 


```php
namespace App;

use DrewM\MailChimp\MailChimp;
use Spatie\Newsletter\Newsletter;
use Spatie\Newsletter\NewsletterListCollection;

class NewsletterFactory
{
    public static function create(string $apiKey): Newsletter
    {
        $mailChimp = new Mailchimp($apiKey);

        $mailChimp->verify_ssl = config('laravel-newsletter.ssl', true);
        // ⬆️ Or you could hard code the value if it's always enabled/disabled

        $configuredLists = NewsletterListCollection::createFromConfig(config('laravel-newsletter'));
        // ⬆️ This might be different per user? Could be a param then
    
        return new Newsletter($mailChimp, $configuredLists);
    }
}
```
