### ISSUE TITLE
firstName and lastName ignored

### ISSUE THREAD

**Issue by SneManden** [spatie/laravel-newsletter#7]
When subscribing a user, I encounted a problem with the first and last name attributes being ignored.

By examining the mailchimp API, it was resolved using `FNAME` and `LNAME` like so:
```
Newsletter::subscribe('rincewind@discworld.com', ['FNAME'=>'Rince', 'LNAME'=>'Wind']);
```

**Comment by freekmurze** [comment]
The merge variables of MailChimp can be named to anything you want. Because the default FNAME and LNAME are not that readable I rename those vars to firstName and lastName in the MailChimp admin.

**Comment by SneManden** [comment]
Ahh OK, didn't know that.

**Comment by m1r0** [comment]
Please consider adding this information to the readme, so people (like me) know that the examples are not using the default API options. Thanks.

**Comment by seblavoie** [comment]
I agree with @m1r0 that this should be more obvious to newcomer. It took me quite a while to understand what was going on, and I understood it from this issue.

What I would suggest is using FNAME and LNAME in the code examples and adding a note explaining that these settings can be change and where to change them in the Mailchimp UI.

I can create a pull request if you want.

**Comment by freekmurze** [comment]
There already is this note in the readme

> Please note the at the time of this writing the default merge variables in MailChimp are named FNAME and LNAME. In our examples we use firstName and lastName for extra readability.

Please send a PR if this note can be written more clearly

**Comment by seblavoie** [comment]
Okay thanks, you are right, I did not see that since I looked at the first code example. 

I think the note is well written, but it is hard to find when scanning the README. Since your code example is pretty self-explanatory, I am pretty sure that many people blindly use the given code as I did.

I would personally go with FNAME and LNAME in the examples and use the note to explain how this can be change on Mailchimp. But that's your call, I also understand why you did it this way. If you want me to make the pull request for the change I am proposing, let me know and I will create it. Otherwise you can close this.

**Comment by freekmurze** [comment]
I've added the note at the top of the readme. It's kinda hard to miss now 😄

**Comment by seblavoie** [comment]
Ah there we go! Yes, this is way better in my opinion. Well played :) 👍
