### ISSUE TITLE
Class 'Newsletter' not found

### ISSUE THREAD

**Issue by ajkerfaisal** [spatie/laravel-newsletter#72]
I am having one issue and maybe this is nothing to do with your component or maybe it is. Any sort of suggestions I appreciated. This component works fine in my local computer. But when I execute Newsletter::subscribe() from server it says:
```
FatalErrorException in MySuperDuperController.php line 21:
Class 'Newsletter' not found
```

BTW: I have already told infrastructure engineer to run composer update and it didn't helped.

**Comment by freekmurze** [comment]
I'm afraid this is problem at your end. You could check if the `spatie/newsletter` directory exist in the `vendor` directory on the server.

(I don't know your specific setup, but you should run `composer install` instead of `composer update` on a production server.

**Comment by fsjdg** [comment]
Hello, I'm having the same issue with an application installed on shared hosting. They usually upload the whole project after 'composer install ...' and 'php artisan vendor:publish ...' in order to "install new packages". It works perfectly on the local environment but got **Class 'Newsletter' not found** on production. Any idea? Thanks in advance!
